import os
import pdb;
print("[info] script start!")
while(1):
    pdb.set_trace()
    print("[info] real_speculative")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=0,1,0 --perf=0,0,0,0 --fq=64 --cp=32 --al=256 --lsq=128 --iq=64 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* real_speculative_stats.txt")
    os.system("mv phase* real_speculative_phase.txt")
    print("[info] real_oracle")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=1,0,0 --perf=0,0,0,0 --fq=64 --cp=32 --al=256 --lsq=128 --iq=64 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* real_oracle_stats.txt")
    os.system("mv phase* real_oracle_phase.txt")
    print("[info] perfect_speculative")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=0,1,0 --perf=1,0,0,0 --fq=64 --cp=32 --al=256 --lsq=128 --iq=64 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* perfect_speculative_stats.txt")
    os.system("mv phase* perfect_speculative_phase.txt")
    print("[info] perfect_oracle")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=1,0,0 --perf=1,0,0,0 --fq=64 --cp=32 --al=256 --lsq=128 --iq=64 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* perfect_oracle_stats.txt")
    os.system("mv phase* perfect_oracle_phase.txt")
    print("[info] real_speculative_smaller_structures_8_chkpts")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=0,1,0 --perf=0,0,0,0 --fq=64 --cp=8 --al=128 --lsq=64 --iq=32 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* real_speculative_smaller_structures_8_chkpts_stats.txt")
    os.system("mv phase* real_speculative_smaller_structures_8_chkpts_phase.txt")
    print("[info] perfect_oracle_smaller_structures_4_chkpts")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=1,0,0 --perf=1,0,0,0 --fq=64 --cp=4 --al=128 --lsq=64 --iq=32 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* perfect_oracle_smaller_structures_4_chkpts_stats.txt")
    os.system("mv phase* perfect_oracle_smaller_structures_4_chkpts_phase.txt")
    print("[info] real_speculative_smaller_structures_4_chkpts")
    os.system("make cleanrun SIM_FLAGS_EXTRA='--disambig=0,1,0 --perf=0,0,0,0 --fq=64 --cp=4 --al=128 --lsq=64 --iq=32 --iqnp=4 --fw=4 --dw=4 --iw=8 --rw=4 -e100000000'")
    os.system("mv stats* real_speculative_smaller_structures_4_chkpts_stats.txt")
    os.system("mv phase* real_speculative_smaller_structures_4_chkpts_phase.txt")

print("[info] script end!")
